# hydra:
#   run:
#     dir: ./my_output_dir

root_dir: ${hydra:runtime.cwd}
vocab_size_map:
  TinyStories: 10_000
  owt: 32_000

eval:
  seed: 1234
  save_path: checkpoints/cs336_lm_TinyStories/
  gpu_id: 7
  iteration: 2000
  prompts:
  - Once upon a time
  - Tom and Lily are friends
  - Long long ago, there was a monk living in a temple
  max_new_tokens: 256  # 256 * 4
  temperature: 0.8
  top_k: null
  top_p: 0.9
  repetition_penalty: 1.0

model_type: cs336_lm
model:
  vocab_size: ${vocab_size_map.${dataset_name}}
  context_length: 512
  context_scale: 2
  d_model: 512
  num_layers: 4
  num_heads: 16
  d_ff: 1344
  rope_theta: 10000.0
  tie_word_embeddings: false

dataset_name: TinyStories     # `TinyStories` or `owt`, change as needed
dataset_split: train          # `train` or `valid`, change as needed
tokenizer_dir: ${root_dir}/tokenizers/${dataset_name}_${dataset_split} # save path for tokenizer
tokenizer:
  vocab_path: ${tokenizer_dir}/vocab.pkl
  merges_path: ${tokenizer_dir}/merges.pkl
  special_tokens: ["<|endoftext|>"]