# hydra:
#   run:
#     dir: ./my_output_dir  # save outputs to custom dir

root_dir: ${hydra:runtime.cwd}/assets

dataset_name: TinyStoriesV2     # `TinyStories` or `owt`, change as needed
model_type: cs336_lm
exp_name: ${model_type}_${dataset_name}
dat_dir: ${root_dir}/data/${dataset_name}/bin

vocab_size_map:
  TinyStoriesV2: 10000
  owt: 32000

defaults:
  - _self_
  - model: cs336_lm

paths:
  train_bin: ${dat_dir}/train.bin
  valid_bin: ${dat_dir}/valid.bin
  model_output: checkpoints/${exp_name} # save path for both first train and resume train
  tokenizer_dir: ${root_dir}/tokenizers/fast/${dataset_name}_train # save path for tokenizer

training:
  enable: True
  total_tokens: 327680000  # batch size × total step count × context length × GPU count × grad accu
  seed: 1234
  dtype: float32
  train_batch_size: 128
  eval_batch_size: 128
  train_steps: 5000
  gradient_accumulation_steps: 1
  compile: false
  eval_iterations: 100
  eval_interval: 500
  max_grad_norm: 1.0
  device: cuda
  lr: 0.001
  min_lr: 0.0002
  warmup_ratio: 0.1  # 100
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  log_interval: 20
  save_checkpoints: false
  resume_checkpoint: null   # load checkpoint from current hydra run dir
  test_infer: True

inference:
  prompts:
  - The hotel’s high-ceilinged lobby resembles that of a ski resort
  - On the evening of Oct. 12, couples and families dressed
  - Yang looked up at Blake
  max_new_tokens: 256  # 256 * 4
  temperature: 0.8
  top_k: null
  top_p: 0.9
  repetition_penalty: 1.0

tokenizer:
  vocab_path: ${paths.tokenizer_dir}/vocab.pkl
  merges_path: ${paths.tokenizer_dir}/merges.pkl
  special_tokens: ["<|endoftext|>"]

comet:
  api_key: SJASztLoOjQpW2Sakl2PDV4YZ
  project: Pretrain
  workspace: leg-end
  run_id: Pretrain-Baseline-Trainer